theme = "modern"

[icons]
name = "awesome"


[[block]]
block = "focused_window"
max_width = 40

[[block]]
block = "net"
device = "wlp29s0f3u4"
interval = 3

[[block]]
block = "music"
on_collapsed_click = "mpc play"
buttons = ["prev", "play", "next"]
max_width = 30

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

#[[block]]
#block = "temperature"
#collapsed = true
#interval = 10
#format = "{min}° min, {max}° max, {average}° avg"
#chip = "k10temp-*"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
